spring:
  application:
    name: authsphere

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/authsphere}
    username: ${SPRING_DATASOURCE_USERNAME:authsphere}
    password: ${SPRING_DATASOURCE_PASSWORD:authsphere123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 2000ms

  mail:
    host: ${SPRING_MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${SPRING_MAIL_PORT:2525}
    username: ${MAIL_USERNAME:f9baa17343474c}
    password: ${MAIL_PASSWORD:38df4c990a8a9e}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:ThisIsAVeryLongSecretKeyForJWTSigningThatMustBeAtLeast256BitsLongEnoughForHS256Algorithm!!@@##$$}
  access-token-expiry: 900000
  refresh-token-expiry: 2592000000

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
